### ISSUE TITLE
APP_ROOT value is not valid for Cloud Run deployments

### ISSUE THREAD

**Issue by titosobabas** [edervishaj/laravel-supervisord#1]
Hey! Nice code you share in the community

I was testing it and i've found an issue to give them correct values for the ENV variables you provide in .env.example file:

```
APP_ROOT=app_root_directory_inside_container
QUEUE_CONNECTION=database   # this is set to `sync` in the .env file Laravel provides
QUEUE_OPTIONS="--queue=some_queue --sleep=3 --tries=3"
NUM_PROCS=4
```

Currently i'm trying to deploy a Laravel project inside a docker to Cloud Run, but i'm lost what kind of value should i have to fill in `APP_ROOT` variable, can you provide an example?

I tried with `APP_ROOT=/var/www/html` but i did not have luck

Thanks

**Comment by edervishaj** [comment]
Hi!

Basically APP_ROOT should be your app root directory on a clean Laravel installation, `artisan` must be inside this directory. If you check `supervisord.conf`, its `command` line is executing `php artisan`:

```
command=php %(ENV_APP_ROOT)s/artisan queue:work %(ENV_QUEUE_DRIVER)s %(ENV_OPTIONS)s
```

Let me know if this helps.

**Comment by edervishaj** [comment]
Closing this. Feel free to reopen if facing similar problems.
